name: publish

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Login into crates.io
      run: cargo login ${{ secrets.CRATES_IO }}
    - name: Build binaries in "release" mode
      run: cargo build -r
    - name: "Package for crates.io"
      run: cargo package
    - name: "Publish to crates.io"
      run: cargo publish